### PR TITLE
First draft of theory of transforms

### LINKED ISSUE #7: Draft of Theory of transforms
Draft of Theory of transforms and context of HMC (this will overlap with Introduction somewhat)

### PR DESCRIPTION
**Pull request by sethaxen**
Fixes #7

### CODE REVIEW

**Review by bob-carpenter — APPROVED** [review]
Thanks!

**Comment by bob-carpenter** [comment]
I can't merge until you take off the "draft" status.  I'd rather just keep merging into the main document rather than working on parallel branches.

**Comment by sethaxen** [comment]
I planned to take a few more passes before merging. There are a few parts I'd like to make more explicit. But I can do this in future commits to the main branch as well.

**Comment by bob-carpenter** [comment]
Thanks.  I'll just go ahead and merge then.

**Pull request merged**
